[options]
admin_passwd = $pbkdf2-sha512$600000$5rx37p1zTsk55xyjVKrV2g$j5HqVmLeCVF1aQtcqCc20A.GKLq0AEzKos1DwjB6wSPEDPFouOFz48aroyHk/vQ717K6cvv78vOl/owAHBS3Eg
db_host = False
db_port = False
db_user = odoo16
db_password = odoo16
addons_path = addons, dev
default_productivity_apps = True

